"""Add all daycare management models

Revision ID: 3c22baf615ad
Revises: 
Create Date: 2025-12-26 03:46:05.800454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c22baf615ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_alerts',
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_alerts_alert_type'), 'compliance_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_due_date'), 'compliance_alerts', ['due_date'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_entity_id'), 'compliance_alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_entity_type'), 'compliance_alerts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_is_resolved'), 'compliance_alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_severity'), 'compliance_alerts', ['severity'], unique=False)
    op.create_table('parents',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=False)
    op.create_index(op.f('ix_parents_phone_primary'), 'parents', ['phone_primary'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_announcement_date'), 'announcements', ['announcement_date'], unique=False)
    op.create_index(op.f('ix_announcements_is_active'), 'announcements', ['is_active'], unique=False)
    op.create_index(op.f('ix_announcements_priority'), 'announcements', ['priority'], unique=False)
    op.create_table('children',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('withdrawal_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('photo_date', sa.Date(), nullable=False),
    sa.Column('photo_time', sa.DateTime(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_photo_date'), 'photos', ['photo_date'], unique=False)
    op.create_index(op.f('ix_photos_uploaded_by'), 'photos', ['uploaded_by'], unique=False)
    op.create_table('staff_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(length=100), nullable=False),
    sa.Column('credential_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_credentials_credential_type'), 'staff_credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_staff_credentials_expiration_date'), 'staff_credentials', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_staff_credentials_is_expired'), 'staff_credentials', ['is_expired'], unique=False)
    op.create_index(op.f('ix_staff_credentials_user_id'), 'staff_credentials', ['user_id'], unique=False)
    op.create_table('activities',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_time', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_date'), 'activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_child_id'), 'activities', ['child_id'], unique=False)
    op.create_table('attendance',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_in_by_name', sa.String(length=255), nullable=False),
    sa.Column('check_in_signature_url', sa.String(length=500), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('check_out_by_name', sa.String(length=255), nullable=True),
    sa.Column('check_out_signature_url', sa.String(length=500), nullable=True),
    sa.Column('is_late_pickup', sa.Boolean(), nullable=False),
    sa.Column('late_pickup_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_child_id'), 'attendance', ['child_id'], unique=False)
    op.create_table('authorized_pickup',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('identification_notes', sa.Text(), nullable=True),
    sa.Column('requires_password', sa.Boolean(), nullable=False),
    sa.Column('password_hint', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_pickup_child_id'), 'authorized_pickup', ['child_id'], unique=False)
    op.create_index(op.f('ix_authorized_pickup_is_active'), 'authorized_pickup', ['is_active'], unique=False)
    op.create_table('child_parents',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('has_custody', sa.Boolean(), nullable=False),
    sa.Column('can_pickup', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_parents_child_id'), 'child_parents', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_parents_parent_id'), 'child_parents', ['parent_id'], unique=False)
    op.create_table('child_photos',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_photos_child_id'), 'child_photos', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_photos_photo_id'), 'child_photos', ['photo_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('overall_mood', sa.String(length=50), nullable=True),
    sa.Column('sent_to_parents', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('activities_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_child_id'), 'daily_reports', ['child_id'], unique=False)
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_reports_sent_to_parents'), 'daily_reports', ['sent_to_parents'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_child_id'), 'emergency_contacts', ['child_id'], unique=False)
    op.create_table('enrollment_forms',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('parent_signature_url', sa.String(length=500), nullable=True),
    sa.Column('parent_signed_at', sa.DateTime(), nullable=True),
    sa.Column('staff_signature_url', sa.String(length=500), nullable=True),
    sa.Column('staff_signed_at', sa.DateTime(), nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_forms_child_id'), 'enrollment_forms', ['child_id'], unique=True)
    op.create_index(op.f('ix_enrollment_forms_enrollment_date'), 'enrollment_forms', ['enrollment_date'], unique=False)
    op.create_index(op.f('ix_enrollment_forms_is_complete'), 'enrollment_forms', ['is_complete'], unique=False)
    op.create_table('immunization_records',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False),
    sa.Column('administration_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunization_records_child_id'), 'immunization_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_immunization_records_expiration_date'), 'immunization_records', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_immunization_records_vaccine_name'), 'immunization_records', ['vaccine_name'], unique=False)
    op.create_table('incident_reports',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.Time(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('circumstances', sa.Text(), nullable=False),
    sa.Column('injury_description', sa.Text(), nullable=True),
    sa.Column('body_part_affected', sa.String(length=100), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('witnesses', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('parent_notified_at', sa.DateTime(), nullable=True),
    sa.Column('parent_notification_method', sa.String(length=50), nullable=True),
    sa.Column('dcfs_notification_required', sa.Boolean(), nullable=False),
    sa.Column('dcfs_notified_at', sa.DateTime(), nullable=True),
    sa.Column('staff_signature_url', sa.String(length=500), nullable=True),
    sa.Column('staff_signed_at', sa.DateTime(), nullable=True),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_child_id'), 'incident_reports', ['child_id'], unique=False)
    op.create_index(op.f('ix_incident_reports_dcfs_notification_required'), 'incident_reports', ['dcfs_notification_required'], unique=False)
    op.create_index(op.f('ix_incident_reports_incident_date'), 'incident_reports', ['incident_date'], unique=False)
    op.create_index(op.f('ix_incident_reports_incident_type'), 'incident_reports', ['incident_type'], unique=False)
    op.create_table('medication_authorizations',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('administration_instructions', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribing_doctor', sa.String(length=255), nullable=True),
    sa.Column('parent_signature_url', sa.String(length=500), nullable=True),
    sa.Column('parent_signed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_authorizations_child_id'), 'medication_authorizations', ['child_id'], unique=False)
    op.create_index(op.f('ix_medication_authorizations_end_date'), 'medication_authorizations', ['end_date'], unique=False)
    op.create_index(op.f('ix_medication_authorizations_is_active'), 'medication_authorizations', ['is_active'], unique=False)
    op.create_table('medication_logs',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('authorization_id', sa.UUID(), nullable=False),
    sa.Column('administration_date', sa.Date(), nullable=False),
    sa.Column('administration_time', sa.Time(), nullable=False),
    sa.Column('dosage_given', sa.String(length=100), nullable=False),
    sa.Column('staff_signature_url', sa.String(length=500), nullable=True),
    sa.Column('administered_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authorization_id'], ['medication_authorizations.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_administration_date'), 'medication_logs', ['administration_date'], unique=False)
    op.create_index(op.f('ix_medication_logs_authorization_id'), 'medication_logs', ['authorization_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_child_id'), 'medication_logs', ['child_id'], unique=False)
    op.create_table('report_photos',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_photos_photo_id'), 'report_photos', ['photo_id'], unique=False)
    op.create_index(op.f('ix_report_photos_report_id'), 'report_photos', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_photos_report_id'), table_name='report_photos')
    op.drop_index(op.f('ix_report_photos_photo_id'), table_name='report_photos')
    op.drop_table('report_photos')
    op.drop_index(op.f('ix_medication_logs_child_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_authorization_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_administration_date'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_medication_authorizations_is_active'), table_name='medication_authorizations')
    op.drop_index(op.f('ix_medication_authorizations_end_date'), table_name='medication_authorizations')
    op.drop_index(op.f('ix_medication_authorizations_child_id'), table_name='medication_authorizations')
    op.drop_table('medication_authorizations')
    op.drop_index(op.f('ix_incident_reports_incident_type'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_incident_date'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_dcfs_notification_required'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_child_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_immunization_records_vaccine_name'), table_name='immunization_records')
    op.drop_index(op.f('ix_immunization_records_expiration_date'), table_name='immunization_records')
    op.drop_index(op.f('ix_immunization_records_child_id'), table_name='immunization_records')
    op.drop_table('immunization_records')
    op.drop_index(op.f('ix_enrollment_forms_is_complete'), table_name='enrollment_forms')
    op.drop_index(op.f('ix_enrollment_forms_enrollment_date'), table_name='enrollment_forms')
    op.drop_index(op.f('ix_enrollment_forms_child_id'), table_name='enrollment_forms')
    op.drop_table('enrollment_forms')
    op.drop_index(op.f('ix_emergency_contacts_child_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_daily_reports_sent_to_parents'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_child_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_child_photos_photo_id'), table_name='child_photos')
    op.drop_index(op.f('ix_child_photos_child_id'), table_name='child_photos')
    op.drop_table('child_photos')
    op.drop_index(op.f('ix_child_parents_parent_id'), table_name='child_parents')
    op.drop_index(op.f('ix_child_parents_child_id'), table_name='child_parents')
    op.drop_table('child_parents')
    op.drop_index(op.f('ix_authorized_pickup_is_active'), table_name='authorized_pickup')
    op.drop_index(op.f('ix_authorized_pickup_child_id'), table_name='authorized_pickup')
    op.drop_table('authorized_pickup')
    op.drop_index(op.f('ix_attendance_child_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_activities_child_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_date'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_staff_credentials_user_id'), table_name='staff_credentials')
    op.drop_index(op.f('ix_staff_credentials_is_expired'), table_name='staff_credentials')
    op.drop_index(op.f('ix_staff_credentials_expiration_date'), table_name='staff_credentials')
    op.drop_index(op.f('ix_staff_credentials_credential_type'), table_name='staff_credentials')
    op.drop_table('staff_credentials')
    op.drop_index(op.f('ix_photos_uploaded_by'), table_name='photos')
    op.drop_index(op.f('ix_photos_photo_date'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('children')
    op.drop_index(op.f('ix_announcements_priority'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_active'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_announcement_date'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parents_phone_primary'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_compliance_alerts_severity'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_is_resolved'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_entity_type'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_entity_id'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_due_date'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_alert_type'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    # ### end Alembic commands ###
